name: CI

on:
  merge_group:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_core:
    name: Build
    uses: ./.github/workflows/build.yml
