name: 'Stencil Playwright Production Release'
on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        default: latest
        type: choice
        description: Which npm tag should this be published to?
        options:
          - latest
          - dev


jobs:
  build_stencil_playwright:
    name: Build
    uses: ./.github/workflows/build.yml

  release_stencil_playwright_production_build:
    name: Publish Stencil Playwright (Production)
    needs: [ build_stencil_playwright ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      # Log the input from GitHub Actions for easy traceability
      - name: Log GitHub Workflow UI Input
        run: |
          echo "Tag: ${{ inputs.tag }}"
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: 'main'

      - name: Get the Version String
        id: version_retrieval
        run: |
          VERSION_STR=$(jq '.version' package.json | sed s/\"//g)
          echo "VERSION_STR=$VERSION_STR" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Print Version String
        run: |
          echo Version: ${{ steps.version_retrieval.outputs.VERSION_STR }}
        shell: bash
